languageCode = "en-us"
title = "Reasonable Performance"
baseurl = "https://vfoley.xyz"
theme = "mftheme"
rssURI = "rss.xml"

[author]
    name = "Vincent Foley"
    github = "gnuvince"

[markup.goldmark.renderer]
unsafe= true
